///*
//// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
//import org.openqa.selenium.Dimen  sion;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//import java.util.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//public class TestTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  @Before
//  public void setUp() {
//    driver = new FirefoxDriver();
//    js = (JavascriptExecutor) driver;
//    vars = new HashMap<String, Object>();
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void test() {
//    driver.get("https://demoqa.com/automation-practice-form");
//    driver.manage().window().setSize(new Dimension(868, 693));
//    driver.findElement(By.id("firstName")).click();
//    driver.findElement(By.id("firstName")).sendKeys("a");
//    driver.findElement(By.id("lastName")).click();
//    driver.findElement(By.id("lastName")).sendKeys("b");
//    driver.findElement(By.id("userEmail")).click();
//    driver.findElement(By.id("userEmail")).sendKeys("email");
//    driver.findElement(By.cssSelector(".custom-radio:nth-child(1) > .custom-control-label")).click();
//    driver.findElement(By.id("userNumber")).click();
//    driver.findElement(By.id("userNumber")).sendKeys("123");
//    driver.findElement(By.id("dateOfBirthInput")).click();
//    driver.findElement(By.cssSelector(".react-datepicker__month-select")).click();
//    {
//      WebElement dropdown = driver.findElement(By.cssSelector(".react-datepicker__month-select"));
//      dropdown.findElement(By.xpath("//option[. = 'April']")).click();
//    }
//    driver.findElement(By.cssSelector(".react-datepicker__month-select > option:nth-child(4)")).click();
//    driver.findElement(By.cssSelector(".react-datepicker__year-select")).click();
//    {
//      WebElement dropdown = driver.findElement(By.cssSelector(".react-datepicker__year-select"));
//      dropdown.findElement(By.xpath("//option[. = '2011']")).click();
//    }
//    driver.findElement(By.cssSelector("option:nth-child(112)")).click();
//    driver.findElement(By.cssSelector(".react-datepicker__day--028:nth-child(5)")).click();
//    driver.findElement(By.cssSelector(".subjects-auto-complete__value-container")).click();
//    driver.findElement(By.cssSelector(".container > .row")).click();
//    driver.findElement(By.id("react-select-2-option-0")).click();
//    driver.findElement(By.cssSelector(".custom-checkbox:nth-child(1) > .custom-control-label")).click();
//    driver.findElement(By.id("currentAddress")).click();
//    driver.findElement(By.id("currentAddress")).sendKeys("test");
//    driver.findElement(By.cssSelector(".col-12:nth-child(3)")).click();
//    driver.findElement(By.cssSelector(".col-12:nth-child(3)")).click();
//  }
//}
//*/
